#4: Pickers component
ripe-tech/ripe-sdk-components-vue pull request #14
Opened 2020-07-31 11:48 UTC by BeeMargarida

| - | - |
| --- | --- |
| Issue | Closes #4 |
| Dependencies | -- |
| Decisions | Pickers using simple default selects and button. **Not** implementing **locales**. |
| Animated GIF | ![pickers](https://user-images.githubusercontent.com/25725586/89032062-b449a080-d32b-11ea-8a5c-1ae3b8eb7ca5.gif)![pickers_configurator](https://user-images.githubusercontent.com/25725586/89032049-ae53bf80-d32b-11ea-8a6b-dac11dc1d69d.gif)|

2020-07-31 14:40 UTC, hugo-gomes requested changes

2020-07-31 14:40 UTC, hugo-gomes commented on vue/components/organisms/ripe-pickers/ripe-pickers.stories.js
> +            /* setTimeout(() => {
remove this

2020-08-03 15:08 UTC, joamag approved these changes

2020-08-03 15:15 UTC, joamag approved these changes

2020-08-03 15:15 UTC, merged