#2: Configurator Component Enhanced
ripe-tech/ripe-sdk-components-vue pull request #15
Opened 2020-07-31 13:40 UTC by BeeMargarida

| - | - |
| --- | --- |
| Issue | Closes #2 |
| Dependencies | -- |
| Decisions | New props (sensitivity, format, useMasks, highlighted and selected part, etc) and now reactive to changes in these props and brand, model, version and parts. |
| Animated GIF | ![config_enh](https://user-images.githubusercontent.com/25725586/89039913-c3841a80-d33a-11ea-8f81-0703f64f32a7.gif)![config_enh1](https://user-images.githubusercontent.com/25725586/89039934-cc74ec00-d33a-11ea-9f20-249f64fd6382.gif)![config_enh2](https://user-images.githubusercontent.com/25725586/89039944-d0087300-d33a-11ea-96c2-9ac7460313cf.gif)![config_enh3](https://user-images.githubusercontent.com/25725586/89039950-d139a000-d33a-11ea-8879-85568c1b60c7.gif)![config_enh4](https://user-images.githubusercontent.com/25725586/89039954-d26acd00-d33a-11ea-87f8-cd4910610fb5.gif)|

2020-07-31 14:47 UTC, hugo-gomes requested changes

2020-07-31 14:47 UTC, hugo-gomes commented on vue/components/organisms/ripe-configurator/ripe-configurator.vue
> +        configAnimate: {
change to `animation`

2020-07-31 14:47 UTC, hugo-gomes commented on vue/components/organisms/ripe-configurator/ripe-configurator.vue
> +            if (!global.ripe) {
for this kind of thing use the following pattern:

```
if (global.ripe) return;
global.ripe = this.ripeData;
```

2020-07-31 15:35 UTC, hugo-gomes approved these changes

2020-08-03 09:28 UTC, joamag approved these changes

2020-08-03 09:28 UTC, merged